version: '3.1'

services:

    web:
        build: .
        restart: unless-stopped
        build:
            context: ./web
            dockerfile: ./Dockerfile
        ports:
        - 80:3000

    db:
        image: bitnami/mariadb
        restart: always
        environment:
            MARIADB_DATABASE: 'cdp'
            MARIADB_USER: 'cdp'
            MARIADB_PASSWORD: 'cdp'
            MARIADB_ROOT_PASSWORD: 'cdp'
        ports: 
            - "3306:3306"
        volumes: 
            - ./db/sql:/docker-entrypoint-initdb.d

    app:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db